### ISSUE TITLE
redirect one-day-geekweek and devops-geekweek

### ISSUE THREAD

**Issue by mcowger** [emccode/training#59]
Given that the {code} team wont be doing these geek weeks moving forward, can I request that the content be archived in some way and a redirect message placed in the README?  The dotnext team is continuing this effort:

https://github.com/dotnext/training

**Comment by kacole2** [comment]
Has it been forked? Do we want to just move the repo?

**Comment by mcowger** [comment]
Well, its not a true fork, as we aren't taking over the docker workstops, mesos workshops, etc.  Just the geek weeks.

So I'm not sure how to handle it - open to suggestions.

**Comment by kacole2** [comment]
@jonasrosland any ideas since this was your baby?

**Comment by mcowger** [comment]
@jonasrosland thoughts?

**Comment by kacole2** [comment]
@jonasrosland ping....

**Comment by jonasrosland** [comment]
Sorry, totally missed this until now. Yeah, let's clean out the old DOGW and just add a redirect link to the dotnext efforts. Makes sense.
